agent:
  hidden_units: 32
  learning_rate: 0.0001
  discount_factor: 0.1
  max_episodes: 5000
  exploration_rate: 1.0
  min_exploration_rate: 0.00001
  exploration_decay_rate: 0.0001
  batch_size: 64
  learning_rate_decay: 0.9995
  min_learning_rate: 0.0000001
  replay_memory_capacity: 10000
  target_network_frequency: 50
  lambda: 0.1
  epsilon: 1.0
  e_decay_function: 13

