wandb:
  project: "july-exp-ppo-approx-model-sweep-4"
#  project: "campus-indoor-model"
  entity: "safe-campus"

directories:
  results_directory: "results"
  config_directory: "config"
  policy_directory: "policy"
  model_directory: "policy/model"

environment:
  environment_id: 'CampusGymEnv-v0'
  seed: 100

alpha: 0.9  # Example alpha value, change as needed
