agent:
  hidden_units: 128
  learning_rate: 0.0005
  discount_factor: 0.1
  max_episodes: 1000
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.995
  batch_size: 64
  learning_rate_decay: 0.999
  min_learning_rate: 0.00001
  replay_memory_capacity: 10000
  target_network_frequency: 500
  softmax_temperature: 0.1
  e_decay_function: 2

