agent:
  hidden_units: 128
  learning_rate: 0.0005
  discount_factor: 0.1
  max_episodes: 1000
  exploration_rate: 1.0
  min_exploration_rate: 0.01
  exploration_decay_rate: 0.995
  batch_size: 64
  learning_rate_decay: 0.9995
  min_learning_rate: 0.000001
  replay_memory_capacity: 10000
  target_network_frequency: 500
  lambda: 0.95
  epsilon: 1.0
  e_decay_function: 11
  softmax_temperature: 1.0
  gae_lambda: 0.95
  clip_epsilon: 0.1
  epochs: 10


