agent:
  learning_rate: 0.01 # 1.0use 0.3 for linear decay, 0.0001 for exponential decay
  discount_factor: 0.1
  max_episodes: 10000 # 5000 for single classroom env
  exploration_rate: 1.0
  min_exploration_rate: 0.000001 # for exponential decay linear is 0.0001, 0.000001 for linear
  exploration_decay_rate: 0.00001 # for exponential decay linear is 0.9999, 0.001 for linear
  learning_rate_decay: 0.9999
  min_learning_rate: 0.00001
  checkpoint_interval: 100 # Save model checkpoint after every 100 episodes
  e_decay_function: 3

  logging_file: "agent_log.txt" # Specify the name of the logging file

#checkpoint_interval
#100
#discount_factor
#0.8
#exploration_decay_rate
#0.001
#exploration_rate
#1
#learning_rate
#0.0001
#logging_file
#"agent_log.txt"
#max_episodes
#10,000
#min_exploration_rate
#0.000001
#alpha
#0.9